export const appTheme = 'APP/SET_THEME'
export const appThemeColors = 'APP/SET_THEME_COLORS'
export const appDrawerFixed = 'APP/SET_DRAWER_FIXED'
export const appDrawerFolded = 'APP/SET_DRAWER_FOLDED'
export const appDrawerDock = 'APP/SET_DRAWER_DOCK'
export const appDrawerTheme = 'APP/SET_DRAWER_THEME'
